# First stage: Generate Nuxt app
FROM loeken/enso-template-base-dev:3.18 as base

# Install necessary tools and dependencies
RUN sudo apk add --no-cache python3 py3-pip

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .
RUN sudo chown -R vscode:vscode /app
RUN git config --global --add safe.directory /app

CMD ["tail", "-f", "/dev/null"]
